spring:
  application:
  name : crud

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: admin
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: true


#logging.level.org.springframework=debug
#logging.level.org.hibernate=debug